
SELECT * FROM Org
SELECT * FROM DanBaoFangShi
SELECT * FROM Direction
SELECT * FROM Import
SELECT * FROM ImportItem
SELECT * FROM ImportLoan
SELECT * FROM ImportPublic
SELECT * FROM ImportPrivate
SELECT * FROM ImportNonAccrual
SELECT * FROM ImportOverdue
SELECT * FROM ImportYWNei
SELECT * FROM ImportYWWai
SELECT * FROM SourceTable
SELECT * FROM SourceTableSheet
SELECT * FROM SourceTableSheetColumn
SELECT * FROM TargetTable
SELECT * FROM TargetTableSheet
SELECT * FROM TargetTableSheetColumn
SELECT * FROM TableMapping
